import { Link } from 'react-router-dom'
import { PrivacyInformation } from '@/components/privacy/PrivacyInformation'
import { LegalPageLayout, LegalSection } from '@/components/privacy/LegalPageLayout'
import { SiteFooter } from '@/components/SiteFooter'
import { useLanguage } from '@/lib/language'

function ContactLink() {
  return <a href="mailto:criteriaappportugal@gmail.com" className="font-semibold text-primary underline underline-offset-2">criteriaappportugal@gmail.com</a>
}

const dataPurposes = [
  ['Criar e proteger contas; manter a sessão; processar alterações à conta', 'Create and protect accounts; remember your sign-in; process account changes', 'Prestar o serviço solicitado', 'Provide the service you request'],
  ['Publicar anúncios, encontrar possíveis correspondências, mostrar mapas e entregar mensagens', 'Publish posts, find possible matches, show maps, and deliver messages', 'Prestar o serviço solicitado', 'Provide the service you request'],
  ['Limitar abusos, investigar falhas e manter o serviço seguro', 'Limit abuse, investigate faults, and keep the service secure', 'O nosso interesse legítimo em operar um serviço seguro e fiável', 'Our legitimate interest in operating a safe and reliable service'],
  ['Responder a pedidos de privacidade e cumprir obrigações legais aplicáveis', 'Respond to privacy requests and meet applicable legal duties', 'Obrigação legal, quando aplicável', 'Legal obligation where applicable'],
  ['Análise estatística opcional do site pela Cloudflare, se configurada e permitida', 'Optional Cloudflare website analytics, if configured and allowed', 'O seu consentimento; pode retirá-lo nas Definições', 'Your opt-in choice; you can withdraw it from Settings'],
] as const

export default function PrivacyPage() {
  const { t } = useLanguage()
  return <>
    <LegalPageLayout current="privacy" title={t('Política de Privacidade', 'Privacy Policy')} introduction={t('Que dados a CRITERIA recolhe, para que são necessários, quem os pode ver e como nos contactar. Aplica-se ao site e à aplicação móvel.', 'What CRITERIA collects, why it is needed, who can see it, and how to ask us about it. This covers the website and the mobile app.')}>
      <LegalSection id="privacy-contact" title={t('Responsável pelo tratamento', 'Who is responsible')}>
        <p>{t('Gonçalo Félix é o responsável pelos dados pessoais tratados pela CRITERIA. Para questões ou pedidos sobre privacidade, escreva para', 'Gonçalo Félix is responsible for personal data processed by CRITERIA. For privacy questions or requests, write to')} <ContactLink />.</p>
      </LegalSection>

      <LegalSection id="privacy-data" title={t('Dados que utilizamos', 'Information we use')}>
        <ul className="list-disc space-y-2 pl-5">
          <li><strong className="text-foreground">{t('Dados da conta:', 'Account details:')}</strong> {t('o seu endereço de email, nome, fotografia de perfil opcional, perfil de comprador ou vendedor escolhido e a data em que confirmou ter pelo menos 18 anos. Nas contas com palavra-passe, guardamos uma síntese criptográfica da palavra-passe, não a palavra-passe em texto simples. Se iniciar sessão com Google, recebemos o identificador da sua conta Google, o endereço de email verificado, o nome e a fotografia de perfil disponibilizada pela Google.', 'your email address, name, optional profile photo, selected buyer or seller role, and the time you confirmed you are at least 18. For password accounts, we store a password hash, not the plain password. If you choose Google sign-in, we receive your Google account identifier, verified email address, name, and any profile photo Google makes available.')}</li>
          <li><strong className="text-foreground">{t('Publicações e localização:', 'Posts and location:')}</strong> {t('os anúncios de imóveis e os critérios de compradores incluem os dados, fotografias, preferências, preços, zonas e coordenadas que fornece. A CRITERIA guarda as coordenadas usadas para encontrar correspondências. Os visitantes dos anúncios ativos, mesmo sem conta, veem uma zona aproximada e uma posição arredondada no mapa. Os vendedores elegíveis com sessão iniciada veem os critérios com localização aproximada. As descrições e fotografias podem, ainda assim, revelar uma localização que tenha introduzido.', 'property listings and buyer criteria include the information, photos, preferences, prices, area labels and coordinates you supply. CRITERIA stores the coordinates used for matching. Visitors to active property listings, including people without accounts, see an approximate area and rounded map position. Eligible signed-in sellers see buyer criteria with an approximate location. Free-text descriptions and photos may still reveal a location you enter.')}</li>
          <li><strong className="text-foreground">{t('Conversas:', 'Conversations:')}</strong> {t('guardamos as mensagens e as publicações a que dizem respeito para que os participantes as possam ler na aplicação.', 'messages and the posts they relate to are stored so participants can read them in the app.')}</li>
          <li><strong className="text-foreground">{t('Segurança e apoio:', 'Security and support:')}</strong> {t('usamos sessões de autenticação e ligações de utilização única para proteger a sua conta. A nossa API conta temporariamente os pedidos por endereço IP para limitar abusos. Também recebemos as informações que nos enviar quando nos contactar.', 'authentication sessions and one-time account links are used to secure your account. Our API temporarily counts requests by IP address to limit abuse. We also receive information you send when you contact us.')}</li>
          <li><strong className="text-foreground">{t('Análise estatística opcional do site:', 'Optional website analytics:')}</strong> {t('se o Cloudflare Web Analytics estiver configurado e o permitir, o seu recurso no navegador mede as visualizações iniciais de páginas, caminhos, sites de origem, informações do dispositivo e navegador e desempenho de carregamento. O acompanhamento automático de mudanças de página na aplicação está desativado e o recurso não carrega em ligações de autenticação ou confirmação de conta de utilização única. Não funciona na aplicação móvel. A Cloudflare afirma que o Web Analytics não regista parâmetros de pesquisa dos URL.', 'if Cloudflare Web Analytics is configured and you allow it, its browser beacon measures initial page views, paths, referring sites, device/browser information, and load performance. Automatic tracking of in-app route changes is disabled, and the beacon does not load on single-use authentication or account-confirmation links. It does not run in the mobile app. Cloudflare says its Web Analytics does not log query strings.')}</li>
        </ul>
      </LegalSection>

      <LegalSection id="privacy-purpose" title={t('Para que usamos os dados', 'Why we use it')}>
        <div className="overflow-hidden rounded-lg border border-border">
          <dl className="divide-y divide-border md:hidden">
            {dataPurposes.map(([purposePt, purposeEn, basisPt, basisEn]) => <div key={purposeEn} className="px-4 py-3.5">
              <dt className="font-semibold text-foreground">{t(purposePt, purposeEn)}</dt>
              <dd className="mt-1.5 text-sm leading-relaxed text-muted-foreground"><span className="font-semibold text-foreground">{t('Fundamento: ', 'Basis: ')}</span>{t(basisPt, basisEn)}</dd>
            </div>)}
          </dl>
          <table className="hidden w-full border-collapse text-left md:table">
            <thead className="bg-accent text-foreground"><tr><th scope="col" className="px-4 py-3 font-semibold">{t('Finalidade', 'Purpose')}</th><th scope="col" className="px-4 py-3 font-semibold">{t('Fundamento', 'Basis')}</th></tr></thead>
            <tbody className="divide-y divide-border">
              {dataPurposes.map(([purposePt, purposeEn, basisPt, basisEn]) => <tr key={purposeEn}><td className="w-1/2 px-4 py-3">{t(purposePt, purposeEn)}</td><td className="px-4 py-3">{t(basisPt, basisEn)}</td></tr>)}
            </tbody>
          </table>
        </div>
        <p>{t('A aplicação não tem atualmente publicidade integrada. Nenhuma decisão automatizada determina se pode comprar ou arrendar um imóvel: as correspondências mostram possíveis coincidências para as pessoas avaliarem.', 'The current app has no in-app advertising feature. No automated decision in the app decides whether you can buy or rent a property: matching shows possible overlaps for people to assess.')}</p>
      </LegalSection>

      <LegalSection id="privacy-visibility" title={t('Quem pode ver as suas publicações', 'Who can see what you post')}>
        <p>{t('Qualquer pessoa pode explorar anúncios de imóveis ativos sem conta. Os critérios de compradores são visíveis a membros com sessão iniciada e perfil de vendedor ou ambos. O seu nome e fotografia podem aparecer nas suas publicações, incluindo anúncios públicos de imóveis. O endereço de email da sua conta é privado. Só os participantes de uma conversa podem ler as mensagens na aplicação.', 'Anyone can browse active property listings without an account. Buyer criteria are visible to signed-in members with the seller or both role. Your name and photo can appear with your posts, including public property listings. The email address on your account is private to you. Only conversation participants can read their messages in the app.')}</p>
        <p>{t('Outras pessoas podem guardar ou partilhar informações que vejam antes de as remover. Não inclua uma morada exata, número de telefone ou outros dados sensíveis em textos ou fotografias públicos, a menos que pretenda divulgá-los.', 'People may save or share information they see before you remove it. Do not put a precise street address, phone number, or other sensitive information in public post text or photos unless you intend to share it.')}</p>
      </LegalSection>

      <LegalSection id="privacy-providers" title={t('Serviços utilizados', 'Services involved')}>
        <p>{t('Usamos serviços de infraestrutura para operar a aplicação: alojamento do site e da API, uma base de dados PostgreSQL (atualmente Neon), armazenamento de imagens (Cloudflare R2), envio de emails da conta (Resend, se configurado) e Google, se escolher iniciar sessão com Google. Ao abrir um mapa, o navegador pede mosaicos ao fornecedor configurado; o fornecedor predefinido é o OpenStreetMap. Ao procurar uma morada, o navegador envia o texto ao OpenStreetMap Nominatim. Estes pedidos incluem dados normais, como o seu endereço IP.', 'We use infrastructure and service providers to run the app: website and API hosting, a PostgreSQL database (currently Neon), image storage (Cloudflare R2), account email delivery (Resend, when configured), and Google if you choose Google sign-in. When you open a map, your browser requests tiles from the configured provider; the default is OpenStreetMap. When you press Find for an address, your browser sends the text to OpenStreetMap Nominatim. Those map requests include ordinary request information, such as your IP address.')}</p>
        <p>{t('As imagens de publicações antigas ou fotografias de perfil da Google podem continuar a ser carregadas do alojamento original. A aplicação disponibiliza as fontes da interface a partir do próprio serviço. Se permitir a análise estatística opcional do navegador, depois de configurada, o Cloudflare Web Analytics recebe medições de visualização de páginas e desempenho. Os locais de tratamento dos fornecedores e as salvaguardas para transferências internacionais dependem da implementação e dos acordos em vigor; peça-nos os detalhes atuais através de', 'Images from older posts or Google profile photos may still load from their original image host. The app serves its interface fonts itself. If you opt in to optional browser analytics after it is configured, Cloudflare Web Analytics receives page-view and performance measurements. Provider processing locations and any international transfer safeguards depend on the live deployment and provider arrangements; ask us at')} <ContactLink />.</p>
      </LegalSection>

      <LegalSection id="privacy-storage" title={t('Armazenamento no dispositivo e cookies', 'Device storage and cookies')}>
        <div className="border-y border-border py-5 md:py-7"><PrivacyInformation /></div>
        <p>{t('No site, o aviso explica o armazenamento necessário. Se o Cloudflare Web Analytics estiver configurado, apresenta também uma escolha opcional separada. O recurso só carrega depois de selecionar «Permitir análise»; «Apenas essenciais» mantém-no desligado. Pode alterar a escolha nas Definições a qualquer momento. A aplicação móvel não carrega este recurso nem apresenta o aviso do site. A CRITERIA não carrega scripts de publicidade.', 'On the website, the notice explains necessary storage. If Cloudflare Web Analytics is configured, it also offers a separate optional choice. The beacon loads only after you select “Allow analytics”; selecting “Essential only” keeps it off. You can change your choice from Settings at any time. The mobile app does not load this browser beacon or show the website notice. CRITERIA does not load advertising scripts.')}</p>
      </LegalSection>

      <LegalSection id="privacy-retention" title={t('Durante quanto tempo guardamos os dados', 'How long information remains')}>
        <p>{t('A conta, as publicações ativas e arquivadas e as conversas permanecem no serviço enquanto a conta existir. Desativar uma publicação retira-a da pesquisa, mas não apaga o respetivo registo. As ligações de recuperação de palavra-passe e de ações da conta expiram após 30 minutos; o servidor remove os registos expirados segundo o seu calendário de manutenção. Os tokens de acesso expiram após 15 minutos e as sessões de atualização são emitidas com validade de 30 dias.', 'Your account, active and archived posts, and conversations stay in the service while your account exists. Deactivating a post hides it from discovery but does not delete its record. Password-reset and account-action links expire after 30 minutes; the server removes expired link records on its maintenance schedule. Sign-in access tokens expire after 15 minutes, and refresh sessions are issued with a 30-day expiry.')}</p>
        <p>{t('Pode pedir a eliminação da conta nas Definições. Após confirmar pela ligação enviada por email, a aplicação elimina a conta, as publicações, as conversas e os registos relacionados na base de dados, e coloca em fila a remoção das fotografias que carregou. A limpeza das fotografias pode terminar mais tarde se o armazenamento estiver temporariamente indisponível. As cópias em backups e registos de fornecedores podem ter prazos de conservação diferentes; contacte-nos para saber os detalhes operacionais atuais.', 'Settings offers account deletion. After you confirm using the email link, the app deletes your account, posts, conversations, and related database records, and queues removal of your uploaded photos. Photo cleanup may finish later if storage is temporarily unavailable. Copies held in backups and provider logs may have separate retention periods; contact us for the current operational details.')}</p>
      </LegalSection>

      <LegalSection id="privacy-rights" title={t('As suas escolhas e direitos', 'Your choices and rights')}>
        <p>{t('Pode editar o nome, a fotografia de perfil e o perfil de utilização na aplicação. Nas Definições pode pedir a alteração do email, atualizar a palavra-passe, terminar sessão, mudar o tema e pedir a eliminação da conta. Pode solicitar o acesso, retificação, apagamento, limitação ou portabilidade dos seus dados pessoais, ou opor-se quando o tratamento se baseia em interesses legítimos. Estes direitos dependem da lei aplicável e das circunstâncias do pedido. Escreva para', 'You can edit your name, profile photo, and role in the app. Settings lets you request an email change, update a password, sign out, change your theme, and request account deletion. You can ask us to access, correct, erase, restrict, or export your personal data, or object where processing relies on legitimate interests. These rights depend on applicable law and the circumstances of your request. Write to')} <ContactLink />; {t('poderemos ter de confirmar que a conta é sua.', 'we may need to verify that the account is yours.')}</p>
        <p>{t('Também pode apresentar uma reclamação à', 'You can also complain to the')} <a href="https://www.cnpd.pt/cidadaos/participacoes/" target="_blank" rel="noopener noreferrer" className="font-semibold text-primary underline underline-offset-2">{t('Comissão Nacional de Proteção de Dados (CNPD)', 'Portuguese Data Protection Authority (CNPD)')}</a> {t('ou a outra autoridade de controlo competente.', 'or another competent supervisory authority.')}</p>
      </LegalSection>

      <LegalSection id="privacy-children" title={t('Idade mínima', 'Age requirement')}>
        <p>{t('A CRITERIA exige que quem cria uma conta confirme ter pelo menos 18 anos. Se considerar que uma pessoa menor de 18 anos criou uma conta, contacte-nos para podermos verificar.', 'CRITERIA requires people creating an account to confirm that they are at least 18. If you believe someone under 18 has created an account, contact us so we can review it.')}</p>
      </LegalSection>

      <LegalSection id="privacy-changes" title={t('Alterações a esta política', 'Changes to this policy')}>
        <p>{t('Podemos atualizar esta página quando o serviço ou os fornecedores mudarem. A data no início indica a última revisão. Daremos conhecimento de alterações relevantes quando apropriado. Para conhecer as regras de utilização do serviço, leia os nossos', 'We may update this page as the service or its providers change. The date at the top shows the latest revision. Material changes will be brought to users’ attention where appropriate. For the rules for using the service, read our')} <Link to="/terms" className="font-semibold text-primary underline underline-offset-2">{t('Termos e Condições', 'Terms of Use')}</Link>.</p>
      </LegalSection>
    </LegalPageLayout>
    <SiteFooter />
  </>
}
