import { Link } from 'react-router-dom'
import { LegalPageLayout, LegalSection } from '@/components/privacy/LegalPageLayout'
import { SiteFooter } from '@/components/SiteFooter'
import { useLanguage } from '@/lib/language'

export default function TermsPage() {
  const { t } = useLanguage()
  return <>
    <LegalPageLayout current="terms" title={t('Termos e Condições', 'Terms of Use')} introduction={t('Estes termos explicam como utilizar a CRITERIA de forma responsável e o que o serviço oferece atualmente. Leia-os antes de criar uma conta ou publicar.', 'These terms explain how to use CRITERIA responsibly and what the service currently does. Please read them before creating an account or posting.')}>
      <LegalSection id="terms-operator" title={t('O serviço e o seu responsável', 'The service and its operator')}>
        <p>{t('A CRITERIA é operada por Gonçalo Félix. Envie dúvidas sobre estes termos, uma publicação ou a utilização do serviço para', 'CRITERIA is operated by Gonçalo Félix. Questions about these terms, a post, or use of the service can be sent to')} <a href="mailto:criteriaappportugal@gmail.com" className="font-semibold text-primary underline underline-offset-2">criteriaappportugal@gmail.com</a>.</p>
        <p>{t('A CRITERIA permite aos membros publicar anúncios de imóveis ou critérios de compradores, descobrir possíveis correspondências e trocar mensagens. Uma correspondência indica que os critérios introduzidos se podem sobrepor; não constitui uma avaliação, verificação, proposta ou garantia de transação. A venda ou o arrendamento de um imóvel é acordado fora da aplicação pelas pessoas envolvidas.', 'CRITERIA lets members publish property listings or buyer criteria, discover possible matches, and exchange messages. A match is an indication that entered criteria overlap; it is not a valuation, verification, offer, or guarantee of a transaction. A property sale or tenancy is arranged outside the app by the people involved.')}</p>
      </LegalSection>

      <LegalSection id="terms-account" title={t('Quem pode criar uma conta', 'Who can use an account')}>
        <p>{t('Tem de ter pelo menos 18 anos para criar uma conta. Forneça dados corretos, mantenha as credenciais de acesso privadas e avise-nos se suspeitar de acesso não autorizado. Escolhe o perfil de comprador, vendedor ou ambos; as funcionalidades disponíveis dependem dessa escolha. O perfil não verifica qualificações profissionais nem a propriedade de um imóvel.', 'You must be at least 18 to create an account. Provide accurate account details, keep your sign-in credentials private, and tell us if you suspect unauthorized access. You choose a buyer, seller, or both role; the features available to you depend on that role. A role does not verify a professional qualification or ownership of a property.')}</p>
        <p>{t('Iniciar sessão com Google é opcional. Se o fizer, os termos da Google também se aplicam à sua relação com a Google. Pode alterar os dados da conta e pedir a sua eliminação nas Definições.', 'Google sign-in is optional. If you use it, Google’s terms also apply to your relationship with Google. You can change account details and request account deletion in Settings.')}</p>
      </LegalSection>

      <LegalSection id="terms-posts" title={t('Anúncios, critérios e mensagens', 'Listings, criteria, and messages')}>
        <p>{t('É responsável pelos dados que envia, incluindo o direito de usar as fotografias que carrega. Mantenha os preços, características dos imóveis, disponibilidade e requisitos corretos e atualizados. Desative uma publicação quando deixar de ser relevante. Não publique dados privados de terceiros, conteúdos enganadores ou ilegais, spam, nem conteúdos que violem direitos de terceiros.', 'You are responsible for the information you submit, including the right to use any photo you upload. Keep prices, property details, availability, and requirements accurate and up to date. Deactivate a post when it is no longer relevant. Do not post another person’s private information, misleading or unlawful material, spam, or content that infringes someone else’s rights.')}</p>
        <p>{t('Qualquer pessoa pode ver um anúncio de imóvel ativo, incluindo o seu nome e fotografia de perfil. Os critérios de compradores são visíveis a vendedores elegíveis com sessão iniciada. As mensagens são visíveis aos participantes da respetiva conversa. Evite incluir dados sensíveis, como uma morada exata, nos textos ou fotografias das publicações se não quiser que outros os vejam.', 'Anyone may see an active property listing, including your name and profile photo. Buyer criteria are visible to eligible signed-in sellers. Messages are visible to the participants in that conversation. Avoid putting sensitive information, including a precise home address, in post text or photos if you do not want others to see it.')}</p>
        <p>{t('Conserva os direitos sobre os conteúdos que envia. Para disponibilizar as funcionalidades que utiliza, autoriza a CRITERIA a guardar, apresentar, redimensionar e transmitir esses conteúdos no serviço enquanto estiverem disponíveis. Esta autorização termina quando os conteúdos são removidos, sem prejuízo de cópias já recebidas por terceiros e da conservação descrita na', 'You keep your rights in content you submit. To operate the features you ask for, you allow CRITERIA to store, display, resize, and transmit that content within the service while it remains available. This permission ends when the content is removed, subject to copies already received by others and the retention described in the')} <Link to="/privacy" className="font-semibold text-primary underline underline-offset-2">{t('Política de Privacidade', 'Privacy Policy')}</Link>.</p>
      </LegalSection>

      <LegalSection id="terms-decisions" title={t('Avalie por si', 'Use your own judgment')}>
        <p>{t('As informações nas publicações são fornecidas pelos membros. A CRITERIA não verifica todas as publicações, identidades, direitos de propriedade, preços ou documentos legais. Confirme os factos importantes por meios independentes antes de transferir dinheiro, assinar um acordo ou visitar um imóvel. Comunique suspeitas de fraude ou publicações inseguras para', 'Information in posts comes from members. CRITERIA does not verify every post, identity, property right, price, or legal document. Check important facts independently before sharing money, signing an agreement, or visiting a property. Report suspected fraud or an unsafe post to')} <a href="mailto:criteriaappportugal@gmail.com" className="font-semibold text-primary underline underline-offset-2">criteriaappportugal@gmail.com</a> {t('com a ligação da publicação e uma breve explicação.', 'with the post link and a short explanation.')}</p>
        <p>{t('Não use a CRITERIA para assediar, discriminar ilegalmente, fazer-se passar por outra pessoa, perturbar o serviço ou enviar promoções não solicitadas a outros membros. Podemos tomar medidas adequadas quando uma publicação ou utilização do serviço viola estes termos ou a lei aplicável, respeitando os direitos dos utilizadores previstos na lei.', 'Do not use CRITERIA to harass, discriminate unlawfully, impersonate someone, interfere with the service, or send unsolicited promotions to other members. We may take appropriate action when a post or use of the service violates these terms or applicable law, subject to any rights users have under applicable law.')}</p>
      </LegalSection>

      <LegalSection id="terms-availability" title={t('Disponibilidade e alterações', 'Availability and changes')}>
        <p>{t('Trabalhamos para manter a CRITERIA disponível e correta, mas os mapas, o envio de emails, a ligação à Internet e outros serviços podem falhar. As publicações também podem deixar de estar disponíveis quando o autor as desativa. Se uma funcionalidade falhar, pode tentar novamente ou contactar-nos.', 'We work to keep CRITERIA available and accurate, but maps, email delivery, connectivity, and other services can fail. Posts may also become unavailable when an owner deactivates them. If a feature fails, you can retry or contact us.')}</p>
        <p>{t('A aplicação não recebe atualmente pagamentos por transações imobiliárias nem inclui um processo de compra. Se forem introduzidas funcionalidades pagas da CRITERIA, o preço e as condições aplicáveis serão apresentados antes de optar por comprá-las. Podemos atualizar a aplicação e estes termos; a data no início indica a última revisão. Daremos conhecimento de alterações relevantes quando apropriado.', 'The current app does not take payments for a property transaction or include a checkout. If paid CRITERIA features are introduced, their price and applicable conditions must be presented before you choose to buy them. We may update the app and these terms; the date at the top shows the latest revision. Material changes will be brought to users’ attention where appropriate.')}</p>
      </LegalSection>

      <LegalSection id="terms-privacy" title={t('Privacidade e serviços externos', 'Privacy and external services')}>
        <p>{t('A', 'The')} <Link to="/privacy" className="font-semibold text-primary underline underline-offset-2">{t('Política de Privacidade', 'Privacy Policy')}</Link> {t('explica que dados pessoais a CRITERIA usa, quem pode ver publicações e mensagens, o armazenamento no dispositivo, a análise estatística opcional do navegador, a eliminação da conta e os serviços externos de mapas, email e autenticação. Os sites e serviços externos têm os seus próprios termos e informações de privacidade.', 'explains the personal information CRITERIA uses, who can see posts and messages, device storage, optional browser analytics, account deletion, and external map, email, and sign-in services. External sites and services have their own terms and privacy information.')}</p>
      </LegalSection>
    </LegalPageLayout>
    <SiteFooter />
  </>
}
